---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: no-helm-temp-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://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@github.com/MOUAK-Ayoub/kubernetes.git
