---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: no-helm-temp-source
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://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@github.com/MOUAK-Ayoub/kubernetes.git
