---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: postgres-chart
  namespace: default
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/MOUAK-Ayoub/kubernetes.git
