---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: no-helm-temp-kustom
  namespace: default
spec:
  interval: 1m0s
  path: ./postgres/on-premises/no-helm-temp
  prune: true
  sourceRef:
    kind: GitRepository
    name: no-helm-temp-source
    namespace: default
  targetNamespace: default
