---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: default
spec:
  channel: gitops-flux
  secretRef:
    name: discord
  type: discord
  username: flux-bot
