---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: nginxhello
  namespace: default
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@example.com
        name: flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 20s
  sourceRef:
    kind: GitRepository
    name: nginxhello
  update:
    path: ./postgres/on-premises/no-helm-tmp
    strategy: Setters

