---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo-postgres-flux
  namespace: default
spec:
  chart:
    spec:
      chart: my-postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres
  interval: 1m0s
