---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres-from-git
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./postgres/on-premises/my-postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: postgres-chart
  interval: 1m0s
  values:
    deployment:
      image:
        version: "12.4"
